package com.Eretail.api.model;
// Generated Sep 19, 2018 12:55:43 PM by Hibernate Tools 4.3.5.Final

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Productlines generated by hbm2java
 */
@Entity
@Table(name = "productlines")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Productlines implements java.io.Serializable {
/**
	 * 
	 */
	private static final long serialVersionUID = -3073380409293467154L;
@Id
private String productLine;
	private String textDescription;
	private String htmlDescription;
	private byte[] image;
	private Set<Products> productses = new HashSet<Products>(0);

	public Productlines() {
	}

	public Productlines(String productLine) {
		this.productLine = productLine;
	}

	
	public Productlines(String productLine, String textDescription, String htmlDescription) {
		super();
		this.productLine = productLine;
		this.textDescription = textDescription;
		this.htmlDescription = htmlDescription;
	}

	public Productlines(String productLine, String textDescription, String htmlDescription, byte[] image,
			Set<Products> productses) {
		this.productLine = productLine;
		this.textDescription = textDescription;
		this.htmlDescription = htmlDescription;
		this.image = image;
		this.productses = productses;
	}

	@Id

	@Column(name = "productLine", unique = true, nullable = false, length = 50)
	public String getProductLine() {
		return this.productLine;
	}

	public void setProductLine(String productLine) {
		this.productLine = productLine;
	}

	@Column(name = "textDescription", length = 4000)
	public String getTextDescription() {
		return this.textDescription;
	}

	public void setTextDescription(String textDescription) {
		this.textDescription = textDescription;
	}

	@Column(name = "htmlDescription", length = 16777215)
	public String getHtmlDescription() {
		return this.htmlDescription;
	}

	public void setHtmlDescription(String htmlDescription) {
		this.htmlDescription = htmlDescription;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productlines")
	@JsonIgnore
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

	@Override
	public String toString() {
		return "Productlines [productLine=" + productLine + ", textDescription=" + textDescription
				+ ", htmlDescription=" + htmlDescription + ", image=" + Arrays.toString(image) + ", productses="
				+ productses + "]";
	}
	
}
